### ISSUE TITLE
error TS2307: Cannot find module 'NgxDraggableResizerModule'.

### ISSUE THREAD

**Issue by Surendranath26** [SenalKumarage/ngx-draggable-resizer#4]
after Doing this step -  

> npm install ngx-draggable-resizer --save

While importing this module into the app.module file, it gives me an error because the library address is not found. please provide correct address to import this module.

**Comment by SenalKumarage** [comment]
@Surendranath26 I have updated the readme. It should be `import { NgxDraggableResizerModule } from 'ngx-draggable-resizer';`. And you can find a working example [here](https://senalkumarage.github.io/ngx-draggable-resizer-demo/). The code to the demo is [here](https://github.com/SenalKumarage/ngx-draggable-resizer-demo).
